version: '3.8'

services:
  python:
    container_name: 'python.${COMPOSE_PROJECT_NAME}'
    build:
      context: '.'
      dockerfile: './docker/python/Dockerfile'
      args:
        python_version: '3.9'
        system_lang: 'en_US.UTF-8'
        system_tz: 'America/Chicago'
    image: '${COMPOSE_PROJECT_NAME}/python'
    volumes:
      - type: 'bind'
        source: '.'
        target: '/workspace'
    tty: true
